version: "3.7"
services:
    frontend:
        container_name: front_react
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        ports:
            - 80:3000
        depends_on:
            - backend
    backend:
        container_name: back_spring
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        ports:
            - 8081:8081
        environment:
            - DB_URL=${DB_URL}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - S3_ACCESSKEY=${S3_ACCESSKEY}
            - S3_SECRETKEY=${S3_SECRETKEY}
            - S3_NAME=${S3_NAME}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
            - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
            - JWT_SECRET=${JWT_SECRET}
            - EC2_PUBLIC_IP=${EC2_PUBLIC_IP}
            - REDIS_PW=${REDIS_PW}
            - OPENVIDU_URL=${OPENVIDU_URL}
            - OPENVIDU_SECRET=${OPENVIDU_SECRET}
